"""bom_model_add_suffix

Revision ID: 04afd703e75e
Revises: cd7af37a0e4e
Create Date: 2026-05-16 20:32:11.131242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04afd703e75e'
down_revision: Union[str, Sequence[str], None] = 'cd7af37a0e4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bom_models', sa.Column('suffix', sa.String(), nullable=True))
    op.execute("UPDATE bom_models SET suffix = '' WHERE suffix IS NULL")
    op.alter_column('bom_models', 'suffix', nullable=False, server_default='')
    op.drop_index(op.f('ix_bom_models_model_code'), table_name='bom_models')
    op.create_index(op.f('ix_bom_models_model_code'), 'bom_models', ['model_code'], unique=False)
    op.create_index(op.f('ix_bom_models_suffix'), 'bom_models', ['suffix'], unique=False)
    op.create_unique_constraint('uq_bom_models_code_suffix', 'bom_models', ['model_code', 'suffix'])
    op.alter_column('item_master', 'lower_vendor_raw',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('item_master', 'inventory_qty',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('item_master', 'defect_qty',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item_master', 'defect_qty',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('item_master', 'inventory_qty',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('item_master', 'lower_vendor_raw',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('uq_bom_models_code_suffix', 'bom_models', type_='unique')
    op.drop_index(op.f('ix_bom_models_suffix'), table_name='bom_models')
    op.drop_index(op.f('ix_bom_models_model_code'), table_name='bom_models')
    op.create_index(op.f('ix_bom_models_model_code'), 'bom_models', ['model_code'], unique=True)
    op.drop_column('bom_models', 'suffix')
    # ### end Alembic commands ###
