"""002_add_daily_qty_json

Revision ID: 5a44df45d409
Revises: 773a5b8ef6e1
Create Date: 2026-04-26 02:54:39.753681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5a44df45d409'
down_revision: Union[str, Sequence[str], None] = '773a5b8ef6e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_plan_lots', sa.Column('daily_qty_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('logistics_efficiency', 'efficiency_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logistics_efficiency', sa.Column('efficiency_rate', sa.DOUBLE_PRECISION(precision=53), sa.Computed('\nCASE\n    WHEN (target_qty > (0)::double precision) THEN (actual_qty / target_qty)\n    ELSE NULL::double precision\nEND', persisted=True), autoincrement=False, nullable=True))
    op.drop_column('daily_plan_lots', 'daily_qty_json')
    # ### end Alembic commands ###
