"""001_initial_schema

Revision ID: 773a5b8ef6e1
Revises: 
Create Date: 2026-04-26 01:42:58.522147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '773a5b8ef6e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_msg', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bom_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bom_models_model_code'), 'bom_models', ['model_code'], unique=True)
    op.create_table('factory_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('zone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('x_coord', sa.Float(), nullable=True),
    sa.Column('y_coord', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factory_locations_code'), 'factory_locations', ['code'], unique=True)
    op.create_table('meeting_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('audio_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transcript', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('participants', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('action_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_lines_code'), 'production_lines', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hashed_pw', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_code'), 'vendors', ['code'], unique=True)
    op.create_table('bom_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('part_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('uom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('vendor_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('supply_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['bom_models.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bom_items_part_model', 'bom_items', ['part_number', 'model_id'], unique=False)
    op.create_index(op.f('ix_bom_items_model_id'), 'bom_items', ['model_id'], unique=False)
    op.create_index(op.f('ix_bom_items_part_number'), 'bom_items', ['part_number'], unique=False)
    op.create_index(op.f('ix_bom_items_path'), 'bom_items', ['path'], unique=False)
    op.create_table('daily_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_date', sa.DateTime(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_date', 'line_id')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_table', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_by', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('part_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('vendor_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tracking_user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tracking_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_master_part_number'), 'item_master', ['part_number'], unique=True)
    op.create_index(op.f('ix_item_master_tracking_user_id'), 'item_master', ['tracking_user_id'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('employee_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('daily_plan_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('wo_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('model_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lot_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('planned_qty', sa.Integer(), nullable=False),
    sa.Column('input_qty', sa.Integer(), nullable=False),
    sa.Column('output_qty', sa.Integer(), nullable=False),
    sa.Column('planned_start', sa.DateTime(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['bom_models.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['daily_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_plan_lots_model_code'), 'daily_plan_lots', ['model_code'], unique=False)
    op.create_index(op.f('ix_daily_plan_lots_plan_id'), 'daily_plan_lots', ['plan_id'], unique=False)
    op.create_table('logistics_efficiency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('target_qty', sa.Float(), nullable=True),
    sa.Column('actual_qty', sa.Float(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('efficiency_rate', sa.Float(), sa.Computed('CASE WHEN target_qty > 0 THEN actual_qty / target_qty ELSE NULL END', persisted=True), nullable=True),
    sa.Column('is_realtime', sa.Boolean(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item_master.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['bom_models.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logistics_efficiency_item_id'), 'logistics_efficiency', ['item_id'], unique=False)
    op.create_index(op.f('ix_logistics_efficiency_recorded_date'), 'logistics_efficiency', ['recorded_date'], unique=False)
    op.create_index(op.f('ix_logistics_efficiency_worker_id'), 'logistics_efficiency', ['worker_id'], unique=False)
    op.create_table('psi_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('psi_date', sa.Date(), nullable=False),
    sa.Column('required_qty', sa.Float(), nullable=False),
    sa.Column('available_qty', sa.Float(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item_master.id'], ),
    sa.ForeignKeyConstraint(['last_updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'psi_date')
    )
    op.create_index(op.f('ix_psi_records_item_id'), 'psi_records', ['item_id'], unique=False)
    op.create_index(op.f('ix_psi_records_psi_date'), 'psi_records', ['psi_date'], unique=False)
    op.create_table('standard_wip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('target_qty', sa.Float(), nullable=False),
    sa.Column('safety_stock', sa.Float(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item_master.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['factory_locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'location_id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('related_item_id', sa.Integer(), nullable=True),
    sa.Column('related_model_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_by_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['related_item_id'], ['item_master.id'], ),
    sa.ForeignKeyConstraint(['related_model_id'], ['bom_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part_list_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('part_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('vendor_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('required_qty', sa.Float(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['daily_plan_lots.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_list_snapshots_lot_id'), 'part_list_snapshots', ['lot_id'], unique=False)
    op.create_index(op.f('ix_part_list_snapshots_part_number'), 'part_list_snapshots', ['part_number'], unique=False)
    op.create_index(op.f('ix_part_list_snapshots_snapshot_date'), 'part_list_snapshots', ['snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_part_list_snapshots_snapshot_date'), table_name='part_list_snapshots')
    op.drop_index(op.f('ix_part_list_snapshots_part_number'), table_name='part_list_snapshots')
    op.drop_index(op.f('ix_part_list_snapshots_lot_id'), table_name='part_list_snapshots')
    op.drop_table('part_list_snapshots')
    op.drop_table('tickets')
    op.drop_table('standard_wip')
    op.drop_index(op.f('ix_psi_records_psi_date'), table_name='psi_records')
    op.drop_index(op.f('ix_psi_records_item_id'), table_name='psi_records')
    op.drop_table('psi_records')
    op.drop_index(op.f('ix_logistics_efficiency_worker_id'), table_name='logistics_efficiency')
    op.drop_index(op.f('ix_logistics_efficiency_recorded_date'), table_name='logistics_efficiency')
    op.drop_index(op.f('ix_logistics_efficiency_item_id'), table_name='logistics_efficiency')
    op.drop_table('logistics_efficiency')
    op.drop_index(op.f('ix_daily_plan_lots_plan_id'), table_name='daily_plan_lots')
    op.drop_index(op.f('ix_daily_plan_lots_model_code'), table_name='daily_plan_lots')
    op.drop_table('daily_plan_lots')
    op.drop_table('workers')
    op.drop_index(op.f('ix_item_master_tracking_user_id'), table_name='item_master')
    op.drop_index(op.f('ix_item_master_part_number'), table_name='item_master')
    op.drop_table('item_master')
    op.drop_table('import_batches')
    op.drop_table('daily_plans')
    op.drop_index(op.f('ix_bom_items_path'), table_name='bom_items')
    op.drop_index(op.f('ix_bom_items_part_number'), table_name='bom_items')
    op.drop_index(op.f('ix_bom_items_model_id'), table_name='bom_items')
    op.drop_index('idx_bom_items_part_model', table_name='bom_items')
    op.drop_table('bom_items')
    op.drop_index(op.f('ix_vendors_code'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_production_lines_code'), table_name='production_lines')
    op.drop_table('production_lines')
    op.drop_table('meeting_records')
    op.drop_index(op.f('ix_factory_locations_code'), table_name='factory_locations')
    op.drop_table('factory_locations')
    op.drop_index(op.f('ix_bom_models_model_code'), table_name='bom_models')
    op.drop_table('bom_models')
    op.drop_table('agent_logs')
    # ### end Alembic commands ###
