"""daily_plan_lot_add_suffix

Revision ID: e727c35d8423
Revises: 0bf21da367dc
Create Date: 2026-05-16 22:18:56.721504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e727c35d8423'
down_revision: Union[str, Sequence[str], None] = '0bf21da367dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_plan_lots', sa.Column('suffix', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_plan_lots', 'suffix')
    # ### end Alembic commands ###
